# path is relative to repo root when running from openint-datahub; or set absolute path
source:
  type: file
  config:
    path: data
    file_type: csv
    platform: openint
    env: PROD
sink:
  type: datahub-rest
  config:
    server: http://localhost:9002
