apiVersion: v1
kind: Service
metadata:
  name: openint-neo4j
  labels:
    app: openint-neo4j
    {{- include "openint.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.neo4j.httpPort }}
      targetPort: {{ .Values.neo4j.httpPort }}
    - name: bolt
      port: {{ .Values.neo4j.boltPort }}
      targetPort: {{ .Values.neo4j.boltPort }}
  selector:
    app: openint-neo4j
