{{- if and .Values.ollama .Values.ollama.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: openint-ollama
  labels:
    app: openint-ollama
    {{- include "openint.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 11434
      targetPort: 11434
      protocol: TCP
  selector:
    app: openint-ollama
{{- end }}
