apiVersion: v1
kind: Service
metadata:
  name: openint-redis
  labels:
    app: openint-redis
    {{- include "openint.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
      protocol: TCP
  selector:
    app: openint-redis
