apiVersion: v1
kind: Service
metadata:
  name: openint-ui
  labels:
    app: openint-ui
    {{- include "openint.labels" . | nindent 4 }}
  {{- if and .Values.ingress .Values.ingress.enabled }}
  annotations:
    cloud.google.com/backend-config: '{"default": "openint-ui-config"}'
    cloud.google.com/neg: '{"ingress": true}'
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ui.port }}
      targetPort: {{ .Values.ui.port }}
      protocol: TCP
  selector:
    app: openint-ui
